### ISSUE TITLE
Isso é realmente necessário?

### ISSUE THREAD

**Issue by MBaltz** [Sekva/proj_compilador#6]
### _Tá no grau_
@Sekva 

https://github.com/Sekva/proj_compilador/blob/9e1aed2d4b22369e3af114b678f4e0bdc2d5cc27/compilador/src/analisador_lexico/token.rs#L15

**Comment by Sekva** [comment]
Ainda não foi implementada a tabela de simbolos, isso vai ser o indice desse token (se um id) na tabela de simbolos
